/**
 * Traction Guest API
 * The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.  # Getting Started If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).  We will also add you to our Slack channel where you can ask questions and get further help.  # Terms and Conditions Please visit: [https://tractionguest.com/tos/api/](https://tractionguest.com/tos/api/)  # Versioning This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.  * The `Major` number increments when potentially incompatible changes are made. * The `Minor` number increments when backwards-compatible additions are made. * The `Patch` number increments when backwards-compatible bug-fixes are made. 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: support@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Host;
import org.openapitools.client.model.Location;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * The data structure for a Group Visit object. Also called an Appointment.
 **/
@ApiModel(description = "The data structure for a Group Visit object. Also called an Appointment.")
public class GroupVisit {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("location")
  private Location location = null;
  @SerializedName("hosts")
  private List<Host> hosts = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("start_time")
  private String startTime = null;
  @SerializedName("end_time")
  private String endTime = null;
  @SerializedName("created_at")
  private String createdAt = null;
  @SerializedName("updated_at")
  private String updatedAt = null;
  @SerializedName("registration_limit")
  private Integer registrationLimit = null;
  @SerializedName("registration_url")
  private String registrationUrl = null;
  @SerializedName("invites_count")
  private Integer invitesCount = null;
  @SerializedName("unconfirmed_registrations_count")
  private Integer unconfirmedRegistrationsCount = null;
  @SerializedName("manual_registration_approval")
  private Boolean manualRegistrationApproval = null;
  @SerializedName("public_registration_enabled")
  private Boolean publicRegistrationEnabled = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Location getLocation() {
    return location;
  }
  public void setLocation(Location location) {
    this.location = location;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Host> getHosts() {
    return hosts;
  }
  public void setHosts(List<Host> hosts) {
    this.hosts = hosts;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStartTime() {
    return startTime;
  }
  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEndTime() {
    return endTime;
  }
  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRegistrationLimit() {
    return registrationLimit;
  }
  public void setRegistrationLimit(Integer registrationLimit) {
    this.registrationLimit = registrationLimit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRegistrationUrl() {
    return registrationUrl;
  }
  public void setRegistrationUrl(String registrationUrl) {
    this.registrationUrl = registrationUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getInvitesCount() {
    return invitesCount;
  }
  public void setInvitesCount(Integer invitesCount) {
    this.invitesCount = invitesCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getUnconfirmedRegistrationsCount() {
    return unconfirmedRegistrationsCount;
  }
  public void setUnconfirmedRegistrationsCount(Integer unconfirmedRegistrationsCount) {
    this.unconfirmedRegistrationsCount = unconfirmedRegistrationsCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getManualRegistrationApproval() {
    return manualRegistrationApproval;
  }
  public void setManualRegistrationApproval(Boolean manualRegistrationApproval) {
    this.manualRegistrationApproval = manualRegistrationApproval;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPublicRegistrationEnabled() {
    return publicRegistrationEnabled;
  }
  public void setPublicRegistrationEnabled(Boolean publicRegistrationEnabled) {
    this.publicRegistrationEnabled = publicRegistrationEnabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupVisit groupVisit = (GroupVisit) o;
    return (this.id == null ? groupVisit.id == null : this.id.equals(groupVisit.id)) &&
        (this.location == null ? groupVisit.location == null : this.location.equals(groupVisit.location)) &&
        (this.hosts == null ? groupVisit.hosts == null : this.hosts.equals(groupVisit.hosts)) &&
        (this.name == null ? groupVisit.name == null : this.name.equals(groupVisit.name)) &&
        (this.startTime == null ? groupVisit.startTime == null : this.startTime.equals(groupVisit.startTime)) &&
        (this.endTime == null ? groupVisit.endTime == null : this.endTime.equals(groupVisit.endTime)) &&
        (this.createdAt == null ? groupVisit.createdAt == null : this.createdAt.equals(groupVisit.createdAt)) &&
        (this.updatedAt == null ? groupVisit.updatedAt == null : this.updatedAt.equals(groupVisit.updatedAt)) &&
        (this.registrationLimit == null ? groupVisit.registrationLimit == null : this.registrationLimit.equals(groupVisit.registrationLimit)) &&
        (this.registrationUrl == null ? groupVisit.registrationUrl == null : this.registrationUrl.equals(groupVisit.registrationUrl)) &&
        (this.invitesCount == null ? groupVisit.invitesCount == null : this.invitesCount.equals(groupVisit.invitesCount)) &&
        (this.unconfirmedRegistrationsCount == null ? groupVisit.unconfirmedRegistrationsCount == null : this.unconfirmedRegistrationsCount.equals(groupVisit.unconfirmedRegistrationsCount)) &&
        (this.manualRegistrationApproval == null ? groupVisit.manualRegistrationApproval == null : this.manualRegistrationApproval.equals(groupVisit.manualRegistrationApproval)) &&
        (this.publicRegistrationEnabled == null ? groupVisit.publicRegistrationEnabled == null : this.publicRegistrationEnabled.equals(groupVisit.publicRegistrationEnabled));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.location == null ? 0: this.location.hashCode());
    result = 31 * result + (this.hosts == null ? 0: this.hosts.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.startTime == null ? 0: this.startTime.hashCode());
    result = 31 * result + (this.endTime == null ? 0: this.endTime.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    result = 31 * result + (this.registrationLimit == null ? 0: this.registrationLimit.hashCode());
    result = 31 * result + (this.registrationUrl == null ? 0: this.registrationUrl.hashCode());
    result = 31 * result + (this.invitesCount == null ? 0: this.invitesCount.hashCode());
    result = 31 * result + (this.unconfirmedRegistrationsCount == null ? 0: this.unconfirmedRegistrationsCount.hashCode());
    result = 31 * result + (this.manualRegistrationApproval == null ? 0: this.manualRegistrationApproval.hashCode());
    result = 31 * result + (this.publicRegistrationEnabled == null ? 0: this.publicRegistrationEnabled.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupVisit {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  location: ").append(location).append("\n");
    sb.append("  hosts: ").append(hosts).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  startTime: ").append(startTime).append("\n");
    sb.append("  endTime: ").append(endTime).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  registrationLimit: ").append(registrationLimit).append("\n");
    sb.append("  registrationUrl: ").append(registrationUrl).append("\n");
    sb.append("  invitesCount: ").append(invitesCount).append("\n");
    sb.append("  unconfirmedRegistrationsCount: ").append(unconfirmedRegistrationsCount).append("\n");
    sb.append("  manualRegistrationApproval: ").append(manualRegistrationApproval).append("\n");
    sb.append("  publicRegistrationEnabled: ").append(publicRegistrationEnabled).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
