/**
 * Traction Guest API
 * The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.  # Getting Started If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).  We will also add you to our Slack channel where you can ask questions and get further help.  # Terms and Conditions Please visit: [https://tractionguest.com/tos/api/](https://tractionguest.com/tos/api/)  # Versioning This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.  * The `Major` number increments when potentially incompatible changes are made. * The `Minor` number increments when backwards-compatible additions are made. * The `Patch` number increments when backwards-compatible bug-fixes are made. 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: support@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InviteCreateParamsParkingStall {
  
  @SerializedName("stall_number")
  private Integer stallNumber = null;
  @SerializedName("parking_lot_id")
  private Integer parkingLotId = null;
  @SerializedName("parking_stall_id")
  private Integer parkingStallId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStallNumber() {
    return stallNumber;
  }
  public void setStallNumber(Integer stallNumber) {
    this.stallNumber = stallNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getParkingLotId() {
    return parkingLotId;
  }
  public void setParkingLotId(Integer parkingLotId) {
    this.parkingLotId = parkingLotId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getParkingStallId() {
    return parkingStallId;
  }
  public void setParkingStallId(Integer parkingStallId) {
    this.parkingStallId = parkingStallId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InviteCreateParamsParkingStall inviteCreateParamsParkingStall = (InviteCreateParamsParkingStall) o;
    return (this.stallNumber == null ? inviteCreateParamsParkingStall.stallNumber == null : this.stallNumber.equals(inviteCreateParamsParkingStall.stallNumber)) &&
        (this.parkingLotId == null ? inviteCreateParamsParkingStall.parkingLotId == null : this.parkingLotId.equals(inviteCreateParamsParkingStall.parkingLotId)) &&
        (this.parkingStallId == null ? inviteCreateParamsParkingStall.parkingStallId == null : this.parkingStallId.equals(inviteCreateParamsParkingStall.parkingStallId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.stallNumber == null ? 0: this.stallNumber.hashCode());
    result = 31 * result + (this.parkingLotId == null ? 0: this.parkingLotId.hashCode());
    result = 31 * result + (this.parkingStallId == null ? 0: this.parkingStallId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InviteCreateParamsParkingStall {\n");
    
    sb.append("  stallNumber: ").append(stallNumber).append("\n");
    sb.append("  parkingLotId: ").append(parkingLotId).append("\n");
    sb.append("  parkingStallId: ").append(parkingStallId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
